"""Initial migration with legal_texts table

Revision ID: 856529c86a85
Revises:
Create Date: 2025-10-08 19:24:02.438617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = "856529c86a85"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legal_texts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_vector", Vector(2560), nullable=False),  # type: ignore
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("section", sa.String(length=50), nullable=False),
        sa.Column("sub_section", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_legal_texts_code"), "legal_texts", ["code"], unique=False)
    op.create_index(op.f("ix_legal_texts_id"), "legal_texts", ["id"], unique=False)
    op.create_index(
        op.f("ix_legal_texts_section"), "legal_texts", ["section"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_legal_texts_section"), table_name="legal_texts")
    op.drop_index(op.f("ix_legal_texts_id"), table_name="legal_texts")
    op.drop_index(op.f("ix_legal_texts_code"), table_name="legal_texts")
    op.drop_table("legal_texts")
    # ### end Alembic commands ###

    # Drop pgvector extension
    op.execute("DROP EXTENSION IF EXISTS vector")
